print('CI calculator')
P=float(input('enter the principal value:'))
R=float(input('enter the rate:'))
N=int(input('enter the number of times interest is compunded:'))
T=int(input('enter the number of years:'))
A=P*(1+(R/N))**(N*T)
print('the compound interest is:',round(A,2))
input()
